name: Generate Datas
on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4  # Updated to the latest version

      # Generate Snake animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Labourguignonn
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Upload artifact (fixed to v4)
      - uses: actions/upload-artifact@v4
        with:
          name: snake-artifact
          path: dist/github-contribution-grid-snake.svg

      # Deploy to GitHub Pages (if needed)
      - uses
