name: Generate Datas
on:
  schedule:
    - cron: "0 */12 * * *"  # Executa a cada 12 horas
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3  # Garante que o repositório é clonado

      # Gera a animação da cobra
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Labourguignonn
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Faz upload do arquivo para checagem
      - uses: actions/upload-artifact@v3
        with:
          name: snake-artifact
          path: dist/github-contribution-grid-snake.svg

      # Publica no branch 'output
