name: Generate Datas
on:
  schedule:
    - cron: "0 */12 * * *"  # Executa a cada 12 horas
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Atualizado para a versão mais recente

      # Gera a animação da cobra
      - name: Generate Snake animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Labourguignonn
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Faz upload do arquivo gerado
      - name: Upload snake animation artifact
        uses: actions/upload-artifact@v4  # Atualizado para a versão mais recente
        with:
          name: snake-artifact
          path: dist/github-contribution-grid-snake.svg

      # Publica no GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
